#!/usr/bin/env bash
# shellcheck disable=SC2048,SC2086
#
# SPDX-FileCopyrightText: 2026 MDP43140
# SPDX-License-Identifier: GPL-3.0-or-later
#
[ $# = 0 ] && {
	echo "This script extracts DNS queries generated by DNSMasq program"
	echo "Usage: $0 [files]"
}

TMP_BLACKLIST_SINKHOLE="$(mktemp -p .)"

sed -E 's/.*dnsmasq\[[0-9]+\]: //' $* \
 | grep -E '^.+ .+ is .+$' \
 | grep -F -e '0.0.0.0' -e '127.0.0.1' \
 | sed -E 's/^.+ (.+) is .+$/\1/' \
 | sed '/\.arpa/d;/\.local/d' \
 | sort -fuib > "${TMP_BLACKLIST_SINKHOLE}";

sed -E 's/.*dnsmasq\[[0-9]+\]: //' $* \
 | grep -E '^(query\[A\]|query\[AAAA\]|forwarded|reply) [^ ]+ (from|to|is) .+$' \
 | grep -Fv -e 'reply error ' \
 | sed -E 's/^(query\[A\]|query\[AAAA\]|forwarded|reply) ([^ ]+) (from|to|is) .+$/\2/' \
 | sed '/\.arpa/d;/\.local/d' \
 | grep -vxF -f "${TMP_BLACKLIST_SINKHOLE}" \
 | sort -fuib;

rm "${TMP_BLACKLIST_SINKHOLE}"
