#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2021-2025 MDP43140
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This script extracts DNS request generated by TCPDump program"
# Usage: $0 [files]"
#        tcpdump | $0"
#
grep -oE 'A\? (.+)\. ' $@ \
 | sed -E 's/^A\? //;s/\. $//' \
 | sort -ui;