#!/usr/bin/env bash
#
# This script extracts DNS request generated by TCPDump program"
# Usage: $0 [files]"
#        tcpdump | $0"
#
grep -oE 'A\? (.+)\. ' $@ \
 | sed -E 's/^A\? //;s/\. $//' \
 | sort -ui;